[project]
name = 'NextOfKin'
description = ''
authors = []
telemetry = true
cache_dir = '.cache'
requirements = []
[contracts.Kin]
path = 'contracts/Kin.clar'
clarity_version = 2
epoch = 2.5

[contracts.Liquid]
path = 'contracts/Liquid.clar'
clarity_version = 1
epoch = 2.05

[contracts.asset]
path = 'contracts/asset.clar'
clarity_version = 1
epoch = 2.05

[contracts.constants]
path = 'contracts/constants.clar'
clarity_version = 2
epoch = 2.5

[contracts.core]
path = 'contracts/core.clar'
clarity_version = 2
epoch = 2.5

[contracts.distrubution]
path = 'contracts/distrubution.clar'
clarity_version = 2
epoch = 2.5

[contracts.main]
path = 'contracts/main.clar'
clarity_version = 2
epoch = 2.5

[contracts.nok-trait]
path = 'contracts/nok-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage]
path = 'contracts/storage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
